config/routes.rb
Rails.application.routes.draw do

#GET------------articles -----------#index ----- articles_path
#GET------------articles/new -------#new ------- new_article_path
#POST-----------articles -----------#create ---- articles_path
#GET -----------articles/:id -------#show ------ article_path(:id)
#GET -----------articles/:id/edit --#edit ------ edit_article_path(:id)
#PATCH/PUT -----articles/:id -------#update ---- article_path(:id)
#DELETE --------articles/:id -------#destroy --- article_path(:id)
#
    devise_for :users

    resources :articles, param: :slug do
      resources :comments
    end

    resources :categories
    post '/search', to: 'search#index', as: 'search'
    get '/result', to: 'search#result', as: 'result'
    get '/locator', to: 'locator#index', as: 'article_locator'

    root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    validates :title, length:{minimum:10, too_short: "%{count} characters is the minimum allowed" }
    validates :content, length:{minimum:10, too_short: "%{count} characters is the minimum allowed" }

    before_validation :slugify

    has_many :comments
    belongs_to :user

    private

    def slugify
        self.slug = self.title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
end

app/models/locator.rb
class Locator < ApplicationRecord

    self.table_name = 'locator';
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    add_flash_types :success, :danger
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    attr_accessor = :title, :content

    before_action :authenticate_user!,
                  only: [:new, :create, :edit, :update, :destroy]

    before_action :find_article, only:[:show,:edit,:destroy,:update]


    def index
        #UPDATE --
        @articles = Article.all
    end

    def show

    end

    def edit
    end

    def create
        @article = Article.new(parameters)
        if  @article.save
            redirect_to article_path(@article.slug), :notice => " L'article a bien été crée"
        else
           render 'new'
        end

    end

    def new
        @article = Article.new
    end



    def update
        if @article.update(parameters)
            redirect_to articles_path, :notice => " L'article a bien été mis a jour"
        else
            render "edit"
        end
    end

    def destroy
        @article.destroy
        redirect_to ({action:'index'}), notice:"article supprimé"
    end


    private

    def parameters
        params[:article][:user_id] = current_user.id
        params.require(:article).permit(:title, :content, :user_id,:slug)
    end

    def find_article
        @article = Article.includes([:comments]).find_by(slug: params[:slug])
    end


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
  end

  def show
      @params = 'test'
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def new
  end

  def create
    @article = Article.where('slug = :slug',slug: params[:article_slug]).first
    @comment = Comment.new(parameters).save

    redirect_back(fallback_location: root_path)
  end

  def update
  end

  def destroy
  end

  private

  def parameters
      params[:comment][:user_id] = current_user.id
      params[:comment][:article_id] = @article.id
      return params[:comment].permit([:comment,:user_id,:article_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        redirect_to articles_url
    end

    def test
        puts 'test'

    end

end

app/controllers/locator_controller.rb
class LocatorController < ApplicationController

    def index
        @articles = Locator.paginate(:page => params[:page], :per_page => 15).order("in_datetime desc")

    
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

before_action :search, only:[:index]


    def index
        render "articles/index"
    end

    private

    def search
      like_search = "%#{params[:search]}%"
      @articles = Article.includes(:comments).where('title LIKE :query',query: like_search)
    end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locator_helper.rb
module LocatorHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/edit.html.erb
<%= form_with scope: :article, url: article_path(@article.slug), method: :put, local: true do |form| %>
    <p>
        <%= form.label :title %>
        <% if @article.errors[:title] %>
        <div class="small " style="color:indianred">
            <%= @article.errors[:title].first %>
        </div>
    <% end %>
    <%= form.text_field :title, class: 'form-control' %>
    </p>

    <p>
        <%= form.label :content %>
        <% if @article.errors[:content] %>
            <div class="small " style="color:indianred">
                <%= @article.errors[:content].first %>
            </div>
        <% end %>
        <%= form.text_area :content, class: 'form-control' %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

<%= link_to('retour aux articles', articles_path) %>

app/views/articles/index.html.erb
<h1 style="padding-bottom:20px">Listes des articles disponibles</h1>


<% @articles.each do |article| %>
    <div class="row border-bottom py-1">

        <div class="col-lg-10">
            <a href="<%= article_path(article.slug) %>">
                <h2><i class="fa fa-angle-right mr-2"></i> <%= article.title %></h2>
            </a>

            <p><%= article.content  %></p>
            <div class="row text-right">
              <div class="col-lg-12">
                <small style="justify-content:right">
                  par <%= article.user.email %>  le <%= article.created_at %>
                </small>
              </div>
            </div>
        </div>

        <% if user_signed_in? && current_user.id.to_s == article.user_id.to_s %>
          <div class="col-lg-2">

              <%= link_to url: edit_article_path(article.slug) do %>
                <i class="fa fa-pencil-alt mr-2" style="color:black"></i>
              <% end %>

              <%= link_to url: article_path(article.slug), method: :delete do %>
                <i class="fa fa-trash mr-2" style="color:indianred"></i>
              <% end %>

          </div>
        <% end %>

    </div>

<% end %>


<div class="row py-4">
  <div class="col-lg-6">
    <%= link_to '< Index', root_path, class:"btn btn-primary" %>
  </div>
  <div class="col-lg-6">
    <%= link_to 'Nouvel article', new_article_path, class:"btn btn-info" %>
  </div>
</div>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title , class:'form-control'%>
    </p>

    <p>
        <%= form.label :content %><br>
        <%= form.text_area :content, class:'form-control' %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %> <br> <small style="font-size:0.5em"> <%= @article.user.email %></small></h1>
<p><%= @article.content  %></p>

<h2>Commentaires :</h2>

<% if user_signed_in? %>
  <%= form_with scope: :comment, url: article_comments_path(@article.slug), method: :post, local: true do |form| %>

      <p>
        <%= form.text_field :comment, class: 'form-control' %>
      </p>

      <p>
          <%= form.submit%>
      </p>
  <% end %>
  <br>
<% end %>

<% @article.comments.each do |comment| %>

  <div class="row">
    <div class="col-lg-12">
      <p> <%= comment.comment %> </p>
      <span><%= comment.created_at %></span>
      <span>user - <%= comment.user.email %></span>
    </div>
  </div>
  <hr>
<% end %>
<div class="row py-4">
  <div class="col-lg-12">
    <%= link_to 'retour au articles', articles_path , class:"btn btn-primary" %>
  </div>
</div>

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/comment/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>

app/views/comment/update.html.erb
<h1>Comment#update</h1>
<p>Find me in app/views/comment/update.html.erb</p>

app/views/locator/index.html.erb
<h1>Articles du locator</h1>

<div class="row">
  <div class="col-lg-12 px-auto">
    <%= will_paginate @articles %>
  </div>
</div>

<table class="table table-border table-hover table-sm">

  <thead>
    <tr>
      <th>ID</th>
      <th>Article</th>
      <th>Description</th>
      <th>état</th>
      <th nowrap >Date d'entrée en stock</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each_with_index do | article, index| %>
        <tr>
          <td><%= article.id_locator %></td>
          <td><%= article.article %></td>
          <td style="font-size:0.7em"><%= article.description.html_safe %></td>
          <td ><%= article.id_etat %></td>
          <td nowrap><%= article.in_datetime %></td>
        </tr>
    <% end %>

  </tbody>
</table>

<div class="row">
  <div class="col-lg-12 px-auto">
    <%= will_paginate @articles %>
  </div>
</div>