config/routes.rb
Rails.application.routes.draw do

#GET------------articles -----------#index ----- articles_path
#GET------------articles/new -------#new ------- new_article_path
#POST-----------articles -----------#create ---- articles_path
#GET -----------articles/:id -------#show ------ article_path(:id)
#GET -----------articles/:id/edit --#edit ------ edit_article_path(:id)
#PATCH/PUT -----articles/:id -------#update ---- article_path(:id)
#DELETE --------articles/:id -------#destroy --- article_path(:id)
#
    devise_for :users

    resources :articles, param: :slug do
      resources :comments
    end

    resources :categories
    post '/search', to: 'search#index', as: 'search'
    get '/result', to: 'search#result', as: 'result'
    get '/locator', to: 'locator#index', as: 'article_locator'

    root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    validates :title, length:{minimum:10, too_short: "%{count} characters is the minimum allowed" }
    validates :content, length:{minimum:10, too_short: "%{count} characters is the minimum allowed" }

    before_validation :slugify

    has_many :comments
    belongs_to :user

    private

    def slugify
        self.slug = self.title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
end

app/models/locator.rb
class Locator < ApplicationRecord

    self.table_name = 'locator';
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    attr_accessor = :title, :content

    before_action :authenticate_user!,
                  only: [:new, :create, :edit, :update, :destroy]

    before_action :find_article, only:[:show,:edit,:destroy,:update]


    def index
        #UPDATE --
        @articles = Article.all
    end

    def show

    end

    def edit
    end

    def create
        @article = Article.new(parameters)
        if  @article.save
            redirect_to article_path(@article.slug), :notice => " L'article a bien été crée"
        else
           render 'new'
        end

    end

    def new
        @article = Article.new
    end



    def update
        if @article.update(parameters)
            redirect_to articles_path, :notice => " L'article a bien été mis a jour"
        else
            render "edit"
        end
    end

    def destroy
        @article.destroy
        redirect_to ({action:'index'}), notice:"article supprimé"
    end


    private

    def parameters
        params[:article][:user_id] = current_user.id
        params.require(:article).permit(:title, :content, :user_id,:slug)
    end

    def find_article
        @article = Article.includes([:comments]).find_by(slug: params[:slug])
    end


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
  end

  def show
      @params = 'test'
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        redirect_to articles_url
    end

    def test
        puts 'test'

    end

end

app/controllers/locator_controller.rb
class LocatorController < ApplicationController

    def index
        @articles = Locator.paginate(:page => params[:page], :per_page => 15).order("in_datetime desc")

    
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

before_action :search, only:[:index]


    def index
        render "articles/index"
    end

    private

    def search
      like_search = "%#{params[:search]}%"
      @articles = Article.includes(:comments).where('title LIKE :query',query: like_search)
    end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locator_helper.rb
module LocatorHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Auth</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"># <b>R</b>ails </a>
    <button class="navbar-toggler"
            type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="<%= articles_path %>">Articles <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Utilitaires
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<%= categories_path %>">Categories</a>
                    <a class="dropdown-item" href="#">Comments</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">User settings</a>
                </div>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">


            <li class="nav-item dropdown">
                <% if user_signed_in? %>
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                        <%= current_user.email %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete">Logout</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">User settings</a>
                    </div>
                <% else %>

                    <a class="mr-2" style="font-size: 1.3em;color:white" href="<%= new_user_session_path %>">Login </a>
                <% end %>

            </li>
            <form class="form-inline m-2 my-lg-0" method="post" action="<%= search_path %>">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Recherche</button>
            </form>
        </ul>

    </div>
</nav>
<div class="container ">
    <div class="row py-3">
        <div class="col-lg-12">
            <div class="row">
                <% if flash[:notice] %>
                    <div class="alert alert-success "
                         style="position: fixed ; right:30px ; bottom:30px">
                        <%= notice %>
                    </div>
                <% end %>
            </div>
            <div class="row">
                <% if flash[:alert] %>
                    <div class="alert alert-danger"
                         style="position: fixed ; right:30px ; bottom:30px">
                    <%= alert %></div>
                <% end %>
            </div>
        </div>
    </div>

      <%= yield %>

</div>

</body>
</html>